#!/usr/bin/env bash

echo "================= delete-object ================"
#Exit imimediately if a command exits with a non-zero status
set -e


# Check for bucket name
if [ -z "$1" ]; then
    echo "Need a bucket name eg. ./delete-object my-bucket-name my-file.txt"
    exit 1
fi


BUCKET_NAME=$1


aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json