#!/usr/bin/env bash

echo "================= SYNC ================"
#Exit imimediately if a command exits with a non-zero status
set -e


# Check for bucket name
if [ -z "$1" ]; then
    echo "Need a bucket name eg. . /bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME =$1

# Check for filename prefix
if [ -z "$2" ]; then
    echo "Need a bucket name eg. . /bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME =$1
FILENAME_PREFIX =$2


#Where will store this files
OUTPUT_DIR="/tmp/s3-bash-scripts"


#ramove the folder if its already there
rm -rf $OUTPUT_DIR

#Lets create the folder
mkdir -p $OUTPUT_DIR

#generate random number
#Determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=NUM_FILES; i++)); do
#Generate random file name
       FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"

#Generate random data and write to file
 dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files